M48
; DRILL file {KiCad 7.0.2-0} date 2024 November 24, Sunday 22:08:24
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-24T22:08:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X145.288Y-63.754
X145.288Y-134.112
X177.8Y-63.754
X177.8Y-134.112
T0
M30
